import React,{useState,useEffect,useRef} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,ActivityIndicator,Alert,KeyboardAvoidingView,Platform} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import * as SecureStore from 'expo-secure-store';
import {GoogleSignin,isSuccessResponse} from '@react-native-google-signin/google-signin';
import {Ionicons} from '@expo/vector-icons';
type Event={kind:string;text?:string;name?:string;args?:Record<string,string>};
type Message={role:string;text:string};
const C={bg:'#080c12',panel:'#111821',line:'#24303e',muted:'#8d9aac',text:'#f2f5fa',accent:'#9cafff'};
const defaults={url:process.env.EXPO_PUBLIC_API_URL||'',model:'gemini-2.5-flash',key:''};
function Button({label,onPress,secondary=false}:{label:string;onPress:()=>void;secondary?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={[s.button,secondary&&s.secondary]}><Text style={{color:secondary?C.text:C.bg,fontWeight:'700'}}>{label}</Text></Pressable>}
function AppContent(){
 const [token,setToken]=useState(''),[name,setName]=useState(''),[ready,setReady]=useState(false),[config,setConfig]=useState(defaults),[tab,setTab]=useState('chat');
 const [messages,setMessages]=useState<Message[]>([]),[events,setEvents]=useState<Event[]>([]),[prompt,setPrompt]=useState(''),[job,setJob]=useState(''),[busy,setBusy]=useState(false),[files,setFiles]=useState<any[]>([]),[expanded,setExpanded]=useState(false),[status,setStatus]=useState('Ready when you are');
 const scroll=useRef<ScrollView>(null);
 const api=async(path:string,method='GET',body?:any,authToken=token)=>{
  if(!/^https:\/\//.test(config.url))throw new Error('Set an HTTPS backend address in Settings.');
  const response=await fetch(config.url.replace(/\/$/,'')+path,{method,headers:{'Content-Type':'application/json',...(authToken?{Authorization:'Bearer '+authToken}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'Request failed');return data;
 };
 const report=(err:any)=>Alert.alert('AetherVM',err.message||String(err));
 useEffect(()=>{(async()=>{try{const raw=await SecureStore.getItemAsync('settings');if(raw)setConfig({...defaults,...JSON.parse(raw)});setToken(await SecureStore.getItemAsync('session')||'');setName(await SecureStore.getItemAsync('name')||'');setJob(await SecureStore.getItemAsync('activeJob')||'');}finally{setReady(true)}})();GoogleSignin.configure({webClientId:process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID});},[]);
 useEffect(()=>{if(token&&ready)api('/messages').then(setMessages).catch(report)},[token,ready]);
 useEffect(()=>{
  if(!job||!token)return;let alive=true;let timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{try{const data=await api('/tasks/'+job);if(!alive)return;setEvents(data.events);setStatus(data.events.filter((e:Event)=>e.kind==='status').at(-1)?.text||'Working…');
   if(data.status!=='running'){setJob('');await SecureStore.deleteItemAsync('activeJob');setStatus(data.status==='done'?'Task complete':data.status);await api('/messages').then(setMessages);if(data.error)Alert.alert('Task stopped',data.error);}
   else timer=setTimeout(poll,1200);
  }catch(err){if(alive){report(err);timer=setTimeout(poll,5000)}}};poll();return()=>{alive=false;clearTimeout(timer)};
 },[job,token]);
 const login=async()=>{setBusy(true);try{if(!process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID)throw new Error('Configure the Google OAuth client ID and rebuild the Android app first.');await GoogleSignin.hasPlayServices();const result=await GoogleSignin.signIn();if(!isSuccessResponse(result))return;if(!result.data.idToken)throw new Error('Google returned no ID token');const data=await api('/auth/google','POST',{id_token:result.data.idToken});await SecureStore.setItemAsync('session',data.token);await SecureStore.setItemAsync('name',data.name);setName(data.name);setToken(data.token);}catch(err){report(err)}finally{setBusy(false)}};
 const send=async()=>{if(!prompt.trim()||job)return;setBusy(true);try{if(!config.key)throw new Error('Add your Gemini API key in Settings first.');const text=prompt.trim();const result=await api('/tasks','POST',{prompt:text,api_key:config.key,model:config.model});setMessages([...messages,{role:'user',text}]);setPrompt('');setEvents([]);setJob(result.id);await SecureStore.setItemAsync('activeJob',result.id);}catch(err){report(err)}finally{setBusy(false)}};
 const save=async()=>{try{if(!/^https:\/\//.test(config.url))throw new Error('Use an HTTPS API address.');await SecureStore.setItemAsync('settings',JSON.stringify(config));Alert.alert('Saved','Your key is stored securely on this device.');setTab('chat');}catch(err){report(err)}};
 const loadFiles=async()=>{setBusy(true);try{const data=await api('/workspace/files');if(data.exit_code!==0)throw new Error(data.output);setFiles(JSON.parse(data.output));setTab('files');}catch(err){report(err)}finally{setBusy(false)}};
 if(!ready)return <View style={s.center}><ActivityIndicator color={C.accent}/></View>;
 return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}><StatusBar style="light"/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}>
 <View style={s.header}><View style={s.logo}><Ionicons name="layers-outline" size={24} color={C.accent}/></View><View style={{flex:1}}><Text style={s.brand}>aether<Text style={{color:C.accent}}>VM</Text></Text><Text style={s.micro}>YOUR IDEAS. A COMPUTER TO ACT.</Text></View><Pressable accessibilityLabel="Settings" onPress={()=>setTab(tab==='settings'?'chat':'settings')} style={s.icon}><Ionicons name="options-outline" size={23} color={C.text}/></Pressable></View>
 {tab==='settings'?<ScrollView contentContainerStyle={s.content}><Text style={s.title}>Make it yours.</Text><Text style={s.sub}>Connect your model and workspace.</Text>{[['url','Backend address','https://api.example.com'],['key','Gemini API key','Your personal API key'],['model','Model ID','gemini-2.5-flash']].map(([field,label,placeholder])=><View key={field} style={{marginTop:24}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} autoCapitalize="none" autoCorrect={false} secureTextEntry={field==='key'} value={(config as any)[field]} placeholder={placeholder} placeholderTextColor={C.muted} onChangeText={value=>setConfig({...config,[field]:value})} style={s.input}/></View>)}<Text style={[s.sub,{marginVertical:20}]}>Your Gemini key is encrypted on this device and sent to your backend only to run a task. Model usage follows your Google API quota.</Text><Button label="Save settings" onPress={save}/>{token&&<><View style={s.card}><Text style={s.label}>Signed in as {name}</Text><Text style={s.sub}>A separate Linux workspace belongs to your account.</Text></View><Button secondary label="Stop workspace" onPress={()=>api('/workspace/stop','POST').then(()=>setStatus('Workspace stopped')).catch(report)}/><Button secondary label="Sign out" onPress={async()=>{try{await api('/auth/logout','POST');await GoogleSignin.signOut();await SecureStore.deleteItemAsync('session');await SecureStore.deleteItemAsync('name');setToken('');setMessages([]);setTab('chat');}catch(err){report(err)}}}/></>}</ScrollView>:
 !token?<View style={[s.content,{flex:1,justifyContent:'center'}]}><View style={s.heroIcon}><Ionicons name="sparkles-outline" size={52} color={C.accent}/></View><Text style={s.title}>An AI with its{ '\n'}own computer.</Text><Text style={[s.sub,{fontSize:17,lineHeight:26,marginVertical:22}]}>From a small idea to a finished project.{ '\n'}Aether works in Linux, while you stay in control.</Text><View style={s.card}><Text style={s.label}>Build · Browse · Automate</Text><Text style={s.sub}>Your Gemini model. Your isolated workspace.</Text></View><Button label={busy?'Connecting…':'Continue with Google'} onPress={login}/><Text style={[s.micro,{textAlign:'center',marginTop:16}]}>CONNECT YOUR BACKEND IN SETTINGS FIRST</Text></View>:
 <><View style={s.tabs}>{['chat','activity','files'].map(t=><Pressable key={t} onPress={()=>t==='files'?loadFiles():setTab(t)} style={[s.tab,tab===t&&s.tabActive]}><Text style={{color:tab===t?C.text:C.muted,textTransform:'capitalize',fontWeight:'600'}}>{t}</Text></Pressable>)}</View>
 <View style={s.status}><View style={[s.dot,{backgroundColor:job?'#a4b5ff':'#79d3ae'}]}/><Text style={s.sub}>{job?'Aether is working':status}</Text><Text numberOfLines={1} style={[s.micro,{marginLeft:'auto',maxWidth:140}]}>{config.model}</Text></View>
 <ScrollView ref={scroll} contentContainerStyle={[s.content,{paddingBottom:25}]} onContentSizeChange={()=>tab==='chat'&&scroll.current?.scrollToEnd({animated:true})}>
 {tab==='chat'&&<>{messages.length===0?<><Text style={[s.micro,{marginTop:36}]}>A WORKSPACE FOR YOUR NEXT IDEA</Text><Text style={[s.title,{marginTop:16}]}>What shall we{ '\n'}bring to life?</Text><Text style={[s.sub,{marginTop:16,marginBottom:28}]}>Give Aether a task. It can write code, organize files and work on the web.</Text>{[['code-slash-outline','Build something','Create a Python expense tracker and test it.'],['globe-outline','Explore the web','Browse python.org and summarize the latest release.'],['folder-open-outline','Work with files','Create a CSV sample dataset and analyze it with Python.']].map(([icon,title,text])=><Pressable key={title} style={s.suggestion} onPress={()=>setPrompt(text)}><Ionicons name={icon as any} size={23} color={C.accent}/><View style={{flex:1}}><Text style={s.label}>{title}</Text><Text style={s.sub}>{text}</Text></View><Ionicons name="arrow-up-outline" size={18} color={C.muted}/></Pressable>)}</>:messages.map((m,i)=><View key={i} style={[s.message,m.role==='user'&&s.userMessage]}><Text style={s.micro}>{m.role==='user'?'YOU':'✧ AETHER'}</Text><Text selectable style={s.messageText}>{m.text}</Text></View>)}
 {job&&<View style={s.message}><Text style={s.micro}>✧ AETHER</Text>{events.filter(e=>e.kind==='text').map((e,i)=><Text key={i} selectable style={s.messageText}>{e.text}</Text>)}<View style={{flexDirection:'row',gap:10,marginTop:16}}><ActivityIndicator color={C.accent}/><Text style={s.sub}>{status}</Text></View><Pressable onPress={()=>setTab('activity')}><Text style={[s.label,{color:C.accent,marginTop:15}]}>View activity →</Text></Pressable></View>}
 {!job&&messages.length>0&&<Pressable onPress={()=>{Alert.alert('New conversation','Clear chat history? Your workspace files will stay.',[{text:'Cancel'},{text:'Clear',onPress:()=>api('/messages','DELETE').then(()=>{setMessages([]);setEvents([])}).catch(report)}])}}><Text style={[s.sub,{textAlign:'center'}]}>Start a new conversation</Text></Pressable>}</>}
 {tab==='activity'&&<><Text style={s.title}>Behind the scenes.</Text><Text style={[s.sub,{marginVertical:16}]}>Commands and results from your latest task.</Text><Pressable onPress={()=>setExpanded(!expanded)}><Text style={s.label}>{expanded?'Hide':'Show'} command output</Text></Pressable>{events.length===0&&<Text style={[s.sub,{marginTop:30}]}>Activity will appear when Aether starts working.</Text>}{events.map((e,i)=><View key={i} style={s.card}><Text style={[s.micro,{color:C.accent}]}>{e.kind==='tool'?e.name:e.kind}</Text>{e.kind==='tool'?<Text selectable style={s.code}>{JSON.stringify(e.args,null,2)}</Text>:e.kind!=='result'||expanded?<Text selectable style={e.kind==='result'?s.code:s.messageText}>{e.text}</Text>:<Text style={s.sub}>Output captured</Text>}</View>)}</>}
 {tab==='files'&&<><Text style={s.title}>Your workspace.</Text><Text style={[s.sub,{marginVertical:16}]}>/workspace · Ask Aether to read or edit any file.</Text>{files.length===0&&<Text style={s.sub}>No files yet. Create something in chat.</Text>}{files.map((f,i)=><Pressable key={i} style={s.suggestion} onPress={()=>{setPrompt('Read and explain '+JSON.stringify('/workspace/'+f.name));setTab('chat')}}><Ionicons name={f.directory?'folder-outline':'document-text-outline'} color={C.accent} size={24}/><Text style={s.label}>{f.name}</Text></Pressable>)}<Button secondary label="Refresh files" onPress={loadFiles}/></>}
 </ScrollView>
 {tab==='chat'&&<View style={s.composerWrap}><View style={s.composer}><TextInput accessibilityLabel="Message Aether" multiline value={prompt} onChangeText={setPrompt} placeholder="Ask Aether to do something…" placeholderTextColor={C.muted} style={s.composeInput}/><Pressable accessibilityLabel={job?'Stop task':'Send message'} disabled={busy||(!job&&!prompt.trim())} onPress={()=>job?api('/tasks/'+job+'/cancel','POST').catch(report):send()} style={[s.send,{opacity:busy||(!job&&!prompt.trim())?0.4:1}]}>{busy?<ActivityIndicator color={C.bg}/>:<Ionicons name={job?'stop':'arrow-up'} color={C.bg} size={22}/>}</Pressable></View><Text style={[s.micro,{textAlign:'center',marginTop:9}]}>AETHER CAN MAKE MISTAKES. CHECK IMPORTANT RESULTS.</Text></View>}</>}
 </KeyboardAvoidingView></SafeAreaView>
}
export default function App(){return <SafeAreaProvider><AppContent/></SafeAreaProvider>}
const s=StyleSheet.create({center:{flex:1,backgroundColor:C.bg,justifyContent:'center'},header:{paddingHorizontal:22,paddingVertical:16,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderColor:C.line},logo:{width:42,height:42,backgroundColor:'#1c2542',borderRadius:14,alignItems:'center',justifyContent:'center'},brand:{fontSize:24,color:C.text,fontWeight:'700',letterSpacing:-1},micro:{fontSize:9,color:C.muted,letterSpacing:1.3,lineHeight:16},icon:{padding:8},content:{padding:24},title:{fontSize:36,lineHeight:43,fontWeight:'600',letterSpacing:-1.2,color:C.text},sub:{fontSize:13,color:C.muted,lineHeight:20},label:{color:C.text,fontSize:15,fontWeight:'600',marginBottom:6},heroIcon:{width:90,height:90,borderRadius:28,backgroundColor:'#18213a',alignItems:'center',justifyContent:'center',marginBottom:32},card:{padding:18,backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:18,marginVertical:12},button:{backgroundColor:C.accent,padding:17,alignItems:'center',borderRadius:15,marginTop:12},secondary:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line},input:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:12,padding:15,color:C.text,fontSize:15},tabs:{flexDirection:'row',gap:6,paddingHorizontal:22,paddingTop:16},tab:{paddingVertical:10,paddingHorizontal:20,borderRadius:12},tabActive:{backgroundColor:'#202a3b'},status:{paddingHorizontal:24,paddingTop:20,flexDirection:'row',alignItems:'center',gap:8},dot:{width:6,height:6,borderRadius:3},suggestion:{padding:18,backgroundColor:C.panel,borderRadius:18,borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',gap:15,marginBottom:12},message:{marginBottom:24},userMessage:{backgroundColor:'#1a2433',borderRadius:18,padding:17,marginLeft:32},messageText:{color:C.text,fontSize:16,lineHeight:25,marginTop:8},code:{fontFamily:'monospace',fontSize:12,lineHeight:19,color:'#bfccdf',marginTop:10},composerWrap:{paddingHorizontal:18,paddingBottom:12,paddingTop:10,borderTopWidth:1,borderColor:C.line},composer:{backgroundColor:C.panel,borderRadius:22,borderWidth:1,borderColor:'#344158',flexDirection:'row',alignItems:'flex-end',padding:10,gap:8},composeInput:{flex:1,color:C.text,fontSize:15,minHeight:42,maxHeight:140,padding:10},send:{width:42,height:42,borderRadius:14,backgroundColor:C.accent,alignItems:'center',justifyContent:'center'}});
