import {StyleSheet,Platform} from 'react-native';
export const C = {
  bg: "#121212",
  rail: "#151719",
  surface: "#1B1E21",
  raised: "#222629",
  line: "#2A2E32",
  text: "#ECEFF1",
  muted: "#949CA4",
  subtle: "#69737D",
  accent: "#B7C6FA",
  accentBg: "#252D40",
  green: "#8FC8A5",
  amber: "#E5BD80",
  red: "#E7A29E",
};
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  app: { flex: 1, flexDirection: "row" },
  main: { flex: 1, minWidth: 0 },
  loading: { flex: 1, alignItems: "center", justifyContent: "center" },
  inline: { flexDirection: "row", alignItems: "center", gap: 10 },
  presence: {
    position: "absolute",
    right: 0,
    bottom: 0,
    borderWidth: 2,
    borderColor: C.bg,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    minHeight: 48,
    backgroundColor: C.text,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 9,
    paddingHorizontal: 18,
    marginTop: 8,
  },
  secondary: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.line,
  },
  buttonText: { color: C.bg, fontWeight: "600", fontSize: 14 },
  smallText: { color: C.text, fontSize: 14, lineHeight: 21 },
  bodyText: { color: C.text, fontSize: 15, lineHeight: 24 },
  caption: { color: C.muted, fontSize: 12, lineHeight: 19 },
  tiny: { color: C.subtle, fontSize: 11, lineHeight: 17 },
  brandName: {
    color: C.text,
    fontSize: 21,
    fontWeight: "600",
    letterSpacing: -0.7,
    flex: 1,
  },
  header: {height:78,flexDirection:'row',alignItems:'center',paddingHorizontal:16,gap:10},
  headerIdentity: {flex:1,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12,paddingVertical:7,minWidth:0,backgroundColor:'#292929',borderWidth:1,borderColor:'#454545',borderRadius:32},
  headerTitle: {color:C.text,fontWeight:'600',fontSize:18,letterSpacing:-.3},
  headerSubtitle: {color:C.muted,fontSize:11,lineHeight:18},
  roster: { flex: 1, backgroundColor: C.rail },
  rosterHead: {
    height: 72,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 22,
    gap: 11,
  },
  newAgent: {
    marginHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    height: 44,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 10,
  },
  agentRow: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 12,
    marginBottom: 5,
  },
  selectedAgent: { backgroundColor: C.raised },
  agentName: { color: C.text, fontSize: 14, fontWeight: "600" },
  rosterFoot: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
    paddingHorizontal: 6,
    paddingBottom: 8,
  },
  accountAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.raised,
    alignItems: "center",
    justifyContent: "center",
  },
  drawerScrim: { flex: 1, backgroundColor: "#00000080", flexDirection: "row" },
  drawer: { height: "100%", maxWidth: 338 },
  transcript: {width:'100%',maxWidth:780,alignSelf:'center',paddingHorizontal:16,paddingTop:6,paddingBottom:24},
  dateDivider: {color:'#757575',fontSize:12,textAlign:'center',paddingVertical:18},
  message: {backgroundColor:'#202020',borderRadius:24,alignSelf:'flex-start',maxWidth:'92%',paddingHorizontal:16,paddingTop:16,paddingBottom:8,marginBottom:12},
  userMessage: {backgroundColor:'#555555',alignSelf:'flex-end',maxWidth:'88%',marginTop:12,marginBottom:14},
  messageText: {color:'#f4f4f4',fontSize:17,lineHeight:25},
  messageTime: {color:C.subtle,fontSize:10,lineHeight:18},
  authorRow: {flexDirection:'row',alignItems:'center',gap:9,marginBottom:13},
  authorName: {color:C.text,fontSize:13,fontWeight:'600',flex:1},
  messageActions: {flexDirection:'row',alignItems:'center',justifyContent:'flex-end',height:34,marginTop:3,opacity:.8},
  emptyChat: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 44,
    maxWidth: 400,
    width: "100%",
    alignSelf: "center",
  },
  emptyTitle: {
    alignSelf: "stretch",
    color: C.text,
    fontSize: 27,
    fontWeight: "500",
    letterSpacing: -0.8,
    textAlign: "center",
    marginTop: 24,
  },
  emptyRole: {
    color: C.muted,
    fontSize: 13,
    lineHeight: 21,
    textAlign: "center",
    marginTop: 6,
  },
  emptyDescription: {
    color: C.muted,
    fontSize: 15,
    lineHeight: 24,
    textAlign: "center",
    marginTop: 19,
    maxWidth: 310,
  },
  suggestions: { width: "100%", maxWidth: 336, marginTop: 30 },
  suggestion: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
  },
  suggestionText: { color: "#C5CBD0", fontSize: 14, flex: 1 },
  composerRegion: {
    width: "100%",
    maxWidth: 780,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 4,
  },
  composer: {flex:1,minWidth:0,flexDirection:'row',flexWrap:'wrap',alignItems:'flex-end',backgroundColor:'#292929',borderWidth:1,borderColor:'#454545',borderRadius:28},
  composerInput: {flex:1,minWidth:80,color:C.text,fontSize:17,lineHeight:24,minHeight:54,maxHeight:150,paddingHorizontal:16,paddingTop:15,paddingBottom:15,textAlignVertical:'top'},
  composerTools: {height:54,width:49,alignItems:'center',justifyContent:'center',paddingRight:5},
  sendButton: {width:38,height:38,borderRadius:19,backgroundColor:C.text,alignItems:'center',justifyContent:'center'},
  modelButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    padding: 8,
    maxWidth: 170,
  },
  composerNote: {
    textAlign: "center",
    color: C.subtle,
    fontSize: 10,
    lineHeight: 17,
    paddingTop: 9,
    paddingBottom: 5,
  },
  setupBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: C.accentBg,
  },
  connectionBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingBottom: 10,
  },
  activityStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    paddingVertical: 18,
  },
  completion: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 16,
  },
  taskError: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 15,
    marginVertical: 12,
    backgroundColor: C.surface,
    borderRadius: 12,
  },
  attention: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
    padding: 16,
    backgroundColor: C.surface,
    borderRadius: 12,
    marginTop: 12,
  },
  attachments: {
    width:"100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    padding: 10,
    paddingBottom: 0,
  },
  attachment: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 8,
    backgroundColor: C.raised,
    padding: 7,
    maxWidth: 220,
  },
  settingsContent: {
    width: "100%",
    maxWidth: 620,
    alignSelf: "center",
    paddingHorizontal: 22,
    paddingBottom: 40,
    paddingTop: 24,
  },
  pageTitle: {
    color: C.text,
    fontSize: 27,
    fontWeight: "500",
    letterSpacing: -0.7,
    marginBottom: 14,
  },
  section: { marginTop: 26 },
  sectionLabel: {
    color: C.subtle,
    fontWeight: "600",
    fontSize: 10,
    letterSpacing: 1.5,
    marginBottom: 10,
  },
  row: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  rowIcon: { width: 30, alignItems: "center" },
  rowTitle: { color: C.text, fontSize: 14, fontWeight: "500", lineHeight: 22 },
  settingsFooter: {
    color: C.subtle,
    fontSize: 11,
    marginTop: 30,
    textAlign: "center",
  },
  scrim: {
    flex: 1,
    backgroundColor: "#000000A0",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 28,
  },
  sheet: {
    backgroundColor: C.rail,
    width: "100%",
    maxWidth: 480,
    maxHeight: "95%",
    borderRadius: 24,
    overflow: "hidden",
  },
  sheetHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 22,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: "600",
    letterSpacing: -0.4,
    color: C.text,
    lineHeight: 29,
  },
  sheetContent: { padding: 24 },
  fieldWrap: { marginBottom: 20 },
  fieldLabel: {
    color: C.muted,
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 9,
  },
  input: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 10,
    padding: 13,
    minHeight: 48,
    color: C.text,
    backgroundColor: C.bg,
    fontSize: 14,
    lineHeight: 22,
  },
  avatarPicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 25,
  },
  avatarOption: {
    padding: 4,
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: 16,
  },
  avatarSelected: { borderColor: C.accent, backgroundColor: C.accentBg },
  profileIntro: {
    flexDirection: "row",
    gap: 18,
    alignItems: "flex-start",
    marginBottom: 19,
  },
  providerIcon: {
    width: 46,
    height: 46,
    backgroundColor: C.accentBg,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  modelRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 46,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  eventRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 12,
  },
  codeText: {
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    fontSize: 12,
    color: "#BEC7CF",
    lineHeight: 20,
    paddingVertical: 7,
  },
  filePreviewEmpty: { alignItems: "center", gap: 20, paddingVertical: 36 },
  login: {
    flex: 1,
    paddingHorizontal: 32,
    maxWidth: 500,
    width: "100%",
    alignSelf: "center",
  },
  loginBrand: {
    minHeight: 80,
    flexDirection: "row",
    gap: 11,
    alignItems: "center",
    paddingTop: 29,
  },
  loginBody: {
    minHeight: 470,
    flex: 1,
    justifyContent: "center",
    paddingBottom: 40,
  },
  loginAvatars: {
    flexDirection: "row",
    gap: 13,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 34,
  },
  loginTitle: {
    color: C.text,
    fontSize: 33,
    lineHeight: 40,
    fontWeight: "500",
    letterSpacing: -1.1,
    textAlign: "center",
  },
  loginDescription: {
    color: C.muted,
    fontSize: 16,
    lineHeight: 25,
    textAlign: "center",
    marginTop: 19,
    marginBottom: 30,
  },
  loginHint: {
    color: C.subtle,
    fontSize: 12,
    textAlign: "center",
    marginTop: 17,
  },
  loginLegal: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 13,
    paddingBottom: 25,
  },
  computer: { flex: 1, backgroundColor: C.bg },
  computerTabs: {
    flexDirection: "row",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  computerTab: {
    height: 54,
    flex: 1,
    maxWidth: 150,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  computerTabSelected: { borderBottomColor: C.accent },
  computerStatus: {
    height: 53,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 22,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  computerEmpty: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
    paddingVertical: 50,
    gap: 10,
    width: "100%",
    maxWidth: 470,
    alignSelf: "center",
  },
  computerIllustration: {
    width: 90,
    height: 90,
    borderRadius: 24,
    backgroundColor: C.surface,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  computerTitle: {
    fontSize: 21,
    color: C.text,
    fontWeight: "500",
    letterSpacing: -0.5,
    textAlign: "center",
    marginTop: 8,
  },
  computerDescription: {
    fontSize: 14,
    color: C.muted,
    lineHeight: 23,
    textAlign: "center",
    marginBottom: 18,
    maxWidth: 330,
  },
  desktopView: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    width: "100%",
    maxWidth: 1100,
    alignSelf: "center",
  },
  screenFrame: {
    backgroundColor: "#08090A",
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    overflow: "hidden",
    width: "100%",
    minHeight: 130,
  },
  controlOwnership: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 17,
  },
  keyboardRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  keyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  keyboardKey: {
    paddingHorizontal: 15,
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: C.surface,
    justifyContent: "center",
  },
  fileToolbar: {
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 8,
  },
  terminalInfo: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 18,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  terminalOutput: { flex: 1, backgroundColor: "#0D0F11" },
  terminalHint: {
    fontFamily: "monospace",
    fontSize: 12,
    color: C.subtle,
    lineHeight: 22,
  },
  terminalComposer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    borderTopWidth: 1,
    borderColor: C.line,
  },
  terminalPrompt: {
    fontFamily: "monospace",
    color: C.accent,
    fontSize: 15,
    paddingLeft: 8,
  },
});
