import React,{useEffect,useRef,useState} from 'react';
import {View,Text,TextInput,Pressable,ActivityIndicator,FlatList,ScrollView,AppState,StyleSheet,Keyboard,Switch} from 'react-native';
import * as Clipboard from 'expo-clipboard';
import {C,s} from '../design';
import {Agent,Api,WorkspaceFile} from '../types';
import {Icon,IconButton,Button,Row,Sheet} from '../ui';
import Avatar from '../components/character/AetherCharacter';
import LiveDesktop from '../components/computer/LiveDesktop';
function fileSize(n:number){return n>1048576?(n/1048576).toFixed(1)+' MB':n>1024?Math.ceil(n/1024)+' KB':n+' B'}
export default function Computer({agent,api,initialState,setComputerState,report,onFile,animations,activity,onBack,onProfile}:{agent?:Agent;api:Api;initialState:string;setComputerState:(s:string)=>void;report:(e:any,title?:string)=>void;onFile:(path:string)=>void;animations:boolean;activity?:string;onBack:()=>void;onProfile:()=>void}){
 const [stream,setStream]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[visible,setVisible]=useState(true),[tab,setTab]=useState('screen'),[panel,setPanel]=useState(''),[trackpad,setTrackpad]=useState(false),[showKeyboard,setShowKeyboard]=useState(false),[typed,setTyped]=useState(''),[files,setFiles]=useState<WorkspaceFile[]>([]),[folder,setFolder]=useState(''),[fileBusy,setFileBusy]=useState(false),[command,setCommand]=useState(''),[terminalBusy,setTerminalBusy]=useState(false),[outputs,setOutputs]=useState<{command:string;output:string;exit_code:number}[]>([]),[viewerCommand,setViewerCommand]=useState<{kind:string;id:number}>();
 const version=useRef(0),inputRef=useRef<TextInput>(null),inputs=useRef(Promise.resolve<any>(undefined)),terminalScroll=useRef<ScrollView>(null);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>setVisible(state==='active'));return()=>sub.remove()},[]);
 const connect=async(reset=true)=>{const v=++version.current;setLoading(true);setError('');setStream(null);try{const start=await api('/workspace/start','POST');const result=await api('/workspace/stream?reset='+String(reset),'POST');if(v!==version.current)return;setComputerState(start.state);setStream(result)}catch(e:any){if(v===version.current)setError(e.message)}finally{if(v===version.current)setLoading(false)}};
 useEffect(()=>{connect(false);return()=>{version.current++}},[api]);
 const input=(action:string,args:any={})=>{inputs.current=inputs.current.catch(()=>{}).then(()=>api('/workspace/input','POST',{action,...args})).catch(e=>report(e,'Could not send computer input'))};
 const type=(next:string)=>{let common=0;while(common<typed.length&&common<next.length&&typed[common]===next[common])common++;for(let n=common;n<typed.length;n++)input('key',{text:'BackSpace'});if(next.slice(common))input('type',{text:next.slice(common)});setTyped(next)};
 const loadFiles=async(path=folder)=>{setFileBusy(true);try{setFiles(await api('/workspace/list?path='+encodeURIComponent(path)));setFolder(path)}catch(e){report(e,'Could not open files')}finally{setFileBusy(false)}};
 const changeTab=(next:string)=>{setPanel('');setTab(next);setShowKeyboard(false);Keyboard.dismiss();if(next==='files')loadFiles()};
 const terminal=async()=>{if(!command.trim()||terminalBusy)return;setTerminalBusy(true);const text=command;setCommand('');try{const result=await api('/workspace/terminal','POST',{command:text});setOutputs(items=>[...items.slice(-39),{command:text,...result}]);terminalScroll.current?.scrollToEnd({animated:animations})}catch(e){setCommand(text);report(e,'Could not run this command')}finally{setTerminalBusy(false)}};
 const clipboard=async(copy:boolean)=>{setPanel('');try{if(copy){const r=await api('/workspace/clipboard');await Clipboard.setStringAsync(r.text)}else{const text=await Clipboard.getStringAsync();if(text){await api('/workspace/clipboard','POST',{text});input('key',{text:'ctrl+v'})}}}catch(e){report(e,'Clipboard unavailable')}};
 const viewer=(kind:string)=>setViewerCommand({kind,id:Date.now()});
 const helpGroups=[{title:'Moving Around',rows:[['scroll','Scroll','Drag with two fingers.'],['pointer','Click and Drag','Tap to click where you tapped. One finger drags.'],['menu','Right-Click','Tap with two fingers, or press and hold.'],['zoom','Zoom In','Pinch to zoom. Zoomed in, two fingers pan instead of scrolling.']]},{title:'Typing and the Clipboard',rows:[['keyboard','Type','Tap the keyboard button in the bottom bar.'],['clipboard','Copy and Paste','Tap the clipboard button for Copy to Phone and Paste from Phone.']]},{title:'When a Pointer Is Easier',rows:[['trackpad','Trackpad Mode','Turn on from the ••• menu. Your finger moves the pointer; tap to click there, double-tap and hold to drag. Recenter it if it drifts.']]}];
 return <View style={[styles.root,{backgroundColor:tab==='screen'?'#000':C.bg}]}>
   <View style={styles.header}>
     <IconButton round name="back" label="Back to conversation" onPress={onBack}/>
     <Pressable accessibilityRole="button" accessibilityLabel="Assistant profile" onPress={onProfile} style={styles.identity}>
       {agent&&<Avatar shape={agent.shape} material={agent.material} size={30} state={activity?'working':'idle'}/>}<Text numberOfLines={1} style={styles.name}>{agent?.name||'Assistant'}</Text>
     </Pressable>
     <IconButton round name="question" label="Using the computer" onPress={()=>setPanel('help')}/>
     <IconButton round name="more" label="Computer options" onPress={()=>setPanel('options')}/>
   </View>
   {tab==='screen'?<>
     <View style={styles.stage}>
       {stream&&visible?<LiveDesktop stream={stream} api={api} visible={visible} trackpad={trackpad} animations={animations} command={viewerCommand} onReady={()=>setError('')} onError={()=>setError('Live connection interrupted. Tap Reconnect in the menu.')}/>:<View style={styles.empty}>
         {loading?<ActivityIndicator color={C.muted}/>:<Icon name="computer" size={42}/>}
         <Text style={styles.emptyTitle}>{loading?'Starting your computer…':error?'Could not connect to the desktop':initialState==='stopped'?'Computer sleeping':'Your Ubuntu computer'}</Text>
         <Text style={styles.description}>{error||'Ubuntu 24.04 · tap the desktop to use it'}</Text>
         {!loading&&<Button label="Reconnect" onPress={()=>connect()}/>}</View>}
       {!!error&&stream&&<Pressable accessibilityRole="button" accessibilityLabel="Reconnect live desktop" onPress={()=>connect()} style={styles.reconnect}><Text style={styles.description}>{error}</Text></Pressable>}
     </View>
     {showKeyboard&&<View style={styles.keyboard}>
       <View style={styles.typing}><TextInput ref={inputRef} autoFocus accessibilityLabel="Type on computer" style={styles.input} value={typed} onChangeText={type} onSubmitEditing={()=>{input('key',{text:'Return'});setTyped('')}} blurOnSubmit={false} autoCapitalize="none" autoCorrect={false} placeholder="Type on the computer…" placeholderTextColor={C.subtle}/><IconButton name="close" label="Hide computer keyboard" onPress={()=>{setShowKeyboard(false);Keyboard.dismiss();setTyped('')}}/></View>
       <View style={styles.keys}>{[['Escape','Esc'],['Tab','Tab'],['Return','Enter'],['ctrl+l','Address'],['ctrl+c','Copy'],['ctrl+v','Paste']].map(([key,label])=><Pressable key={key} accessibilityRole="button" style={styles.key} onPress={()=>input('key',{text:key})}><Text style={styles.keyText}>{label}</Text></Pressable>)}</View>
     </View>}
     <View style={styles.bottom}><IconButton round name="clipboard" label="Computer clipboard" disabled={!stream} onPress={()=>setPanel('clipboard')}/><Text numberOfLines={1} style={styles.subtle}>{trackpad?'Trackpad mode':''}</Text><IconButton round name="keyboard" label="Show computer keyboard" disabled={!stream} onPress={()=>{setTyped('');setShowKeyboard(true);setTimeout(()=>inputRef.current?.focus(),100)}}/></View>
   </>:<>
     <View style={styles.tabs}>{['screen','files','terminal'].map(id=><Pressable key={id} accessibilityRole="tab" accessibilityState={{selected:tab===id}} style={[styles.tab,tab===id&&styles.selected]} onPress={()=>changeTab(id)}><Icon name={id==='screen'?'computer':id==='files'?'folder':'terminal'}/><Text style={s.smallText}>{id[0].toUpperCase()+id.slice(1)}</Text></Pressable>)}</View>
     {tab==='files'?<View style={{flex:1}}><View style={s.fileToolbar}>{!!folder&&<IconButton name="back" label="Parent folder" onPress={()=>loadFiles(folder.split('/').slice(0,-1).join('/'))}/>}<Text style={[s.caption,{flex:1}]}>{folder||'Workspace'}</Text><IconButton name="refresh" label="Refresh files" onPress={()=>loadFiles()}/></View>{fileBusy?<ActivityIndicator color={C.muted}/>:<FlatList data={files} keyExtractor={f=>f.name} contentContainerStyle={{paddingHorizontal:14}} renderItem={({item})=><Row icon={item.directory?'folder':'file'} title={item.name} subtitle={item.directory?'Folder':fileSize(item.size)} onPress={()=>{const p=(folder?folder+'/':'')+item.name;item.directory?loadFiles(p):onFile(p)}}/>}/>}</View>:<View style={styles.terminal}><ScrollView ref={terminalScroll} style={{flex:1}} contentContainerStyle={{padding:18}} onContentSizeChange={()=>terminalScroll.current?.scrollToEnd({animated:animations})} keyboardShouldPersistTaps="handled">{!outputs.length&&<Text style={styles.terminalHint}>Ubuntu terminal · /workspace</Text>}{outputs.map((o,i)=><View key={i} style={{marginBottom:18}}><Text selectable style={styles.shellCommand}>$ {o.command}</Text><Text selectable style={styles.shellOutput}>{o.output||'(no output)'}</Text>{o.exit_code!==0&&<Text style={styles.exit}>Exit code {o.exit_code}</Text>}</View>)}{terminalBusy&&<ActivityIndicator color={C.muted}/>}</ScrollView><View style={styles.terminalInput}><Text style={styles.shellCommand}>$</Text><TextInput accessibilityLabel="Terminal command" value={command} onChangeText={setCommand} onSubmitEditing={terminal} style={styles.input} placeholder="Run a command…" placeholderTextColor={C.subtle} autoCapitalize="none" autoCorrect={false}/><IconButton name="send" label="Run command" disabled={terminalBusy||!command.trim()} onPress={terminal}/></View></View>}
   </>}
   {panel==='help'&&<Sheet title="Using the Computer" onClose={()=>setPanel('')} fullScreen><ScrollView contentContainerStyle={{paddingBottom:24}}>{helpGroups.map(group=><View key={group.title} style={{marginBottom:26}}><Text style={styles.groupTitle}>{group.title}</Text><View style={styles.helpCard}>{group.rows.map(([icon,title,description],i)=><View key={title} style={[styles.helpRow,i!==group.rows.length-1&&styles.divider]}><Icon name={icon} size={23}/><View style={{flex:1}}><Text style={styles.helpTitle}>{title}</Text><Text style={styles.helpDescription}>{description}</Text></View></View>)}</View></View>)}</ScrollView></Sheet>}
   {panel==='options'&&<Sheet title="Computer" onClose={()=>setPanel('')}><Row icon="computer" title="Desktop" onPress={()=>changeTab('screen')}/><Row icon="folder" title="Files" onPress={()=>changeTab('files')}/><Row icon="terminal" title="Terminal" onPress={()=>changeTab('terminal')}/><Row icon="trackpad" title="Trackpad mode" right={<Switch value={trackpad} onValueChange={setTrackpad} accessibilityLabel="Trackpad mode"/>}/><Row icon="pointer" title="Recenter pointer" onPress={()=>{viewer('recenter');setPanel('')}}/><Row icon="zoom" title="Reset zoom" onPress={()=>{viewer('reset');setPanel('')}}/><Row icon="refresh" title="Reconnect" onPress={()=>{setPanel('');connect()}}/><Row icon="pause" title="Put computer to sleep" onPress={async()=>{setPanel('');try{await api('/workspace/stop','POST');setStream(null);setComputerState('stopped')}catch(e){report(e)}}}/></Sheet>}
   {panel==='clipboard'&&<Sheet title="Clipboard" onClose={()=>setPanel('')}><Row icon="copy" title="Copy to Phone" subtitle="Copy the computer’s selected text first." onPress={()=>clipboard(true)}/><Row icon="clipboard" title="Paste from Phone" subtitle="Paste your phone’s clipboard into the computer." onPress={()=>clipboard(false)}/></Sheet>}
 </View>
}
const styles=StyleSheet.create({root:{flex:1},header:{flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:16,paddingVertical:12},identity:{flex:1,flexDirection:'row',alignItems:'center',gap:10,minWidth:0},name:{color:C.text,fontSize:19,fontWeight:'600',flexShrink:1},stage:{flex:1,minHeight:100},empty:{flex:1,justifyContent:'center',alignItems:'center',padding:30,gap:20},emptyTitle:{color:C.text,fontSize:20,textAlign:'center'},description:{color:C.muted,fontSize:14,lineHeight:22,textAlign:'center'},bottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:18,paddingTop:12,paddingBottom:10},subtle:{color:C.muted,fontSize:12,flex:1,textAlign:'center'},reconnect:{position:'absolute',bottom:12,left:20,right:20,padding:12,backgroundColor:'#1d1d1de8',borderRadius:15},keyboard:{backgroundColor:'#171717',paddingHorizontal:12,paddingBottom:8},typing:{flexDirection:'row',alignItems:'center'},input:{flex:1,minHeight:46,color:C.text,fontSize:15,paddingHorizontal:12},keys:{flexDirection:'row',gap:6,justifyContent:'space-between'},key:{paddingVertical:9,paddingHorizontal:9,borderRadius:9,backgroundColor:'#292929'},keyText:{color:C.text,fontSize:12},tabs:{flexDirection:'row',borderBottomWidth:1,borderColor:C.line},tab:{flex:1,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8,paddingVertical:16},selected:{borderBottomWidth:2,borderColor:C.accent},terminal:{flex:1,backgroundColor:'#101010'},terminalInput:{flexDirection:'row',alignItems:'center',paddingHorizontal:14,borderTopWidth:1,borderColor:C.line},terminalHint:{color:C.subtle,fontSize:13,marginBottom:20},shellCommand:{color:'#8dbbff',fontFamily:'monospace',fontSize:13,lineHeight:21},shellOutput:{color:'#d7dadd',fontFamily:'monospace',fontSize:13,lineHeight:21},exit:{color:'#dda99f',fontSize:12,marginTop:8},groupTitle:{color:C.subtle,fontSize:14,marginBottom:12,marginLeft:16},helpCard:{backgroundColor:'#222',borderRadius:24,paddingHorizontal:20},helpRow:{flexDirection:'row',gap:16,paddingVertical:20},divider:{borderBottomWidth:1,borderColor:'#393939'},helpTitle:{color:C.text,fontSize:19,marginBottom:4},helpDescription:{color:C.muted,fontSize:16,lineHeight:24}});
