import React,{useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,FlatList,StyleSheet} from 'react-native';
import AetherCharacter from '../components/character/AetherCharacter';
import {taskState} from '../components/character/appearance';
export type HomeAgent={id:string;name:string;role:string;avatar:number;shape?:string;material?:string;preview?:string;job?:{id:string;status:string;created:number;control?:string;events?:any[]}|null};
export function AgentTile({agent,onOpen}: {agent:HomeAgent;onOpen:()=>void}) {
 return <Pressable onPress={onOpen} accessibilityRole="button" accessibilityLabel={`Open ${agent.name}`} style={({pressed})=>[s.agent,{transform:[{scale:pressed?.97:1}]}]}><AetherCharacter {...agent} variant={agent.avatar} size={116} state={taskState(agent.job)}/><Text numberOfLines={1} style={s.agentName}>{agent.name}</Text><Text numberOfLines={1} style={s.role}>{agent.role}</Text><Text style={[s.presence,{color:agent.job?.status==='waiting'?'#E5BD80':agent.job?.status==='running'?'#8FC8A5':'#949CA4'}]}>{agent.job?.status==='running'?'● Working':agent.job?.status==='waiting'?'● Needs you':agent.job?.status==='error'?'Needs attention':'Ready'}</Text></Pressable>;
}
export default function HomeScreen({name,agents,onOpen,onCreate,onSubmit,busy,mode='home'}:{name:string;agents:HomeAgent[];onOpen:(id:string)=>void;onCreate:()=>void;onSubmit:(text:string,id:string)=>void;busy:boolean;mode?:'home'|'agents'|'activity'}) {
 const [draft,setDraft]=useState(''),[chosen,setChosen]=useState('');
 const target=agents.find(a=>a.id===chosen)||agents.find(a=>a.job?.status!=='running')||agents[0];
 const hour=new Date().getHours(),greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';
 const running=agents.filter(a=>['running','waiting'].includes(a.job?.status||'')),recent=agents.filter(a=>a.job&&!['running','waiting'].includes(a.job.status));
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}>
  <Text style={s.eyebrow}>{mode==='home'?`${greeting}${name?', '+name.split(' ')[0]:''}.`:'AetherVM'}</Text>
  <Text style={s.title}>{mode==='home'?'What should\nwe get done?':mode==='agents'?'Your Aethers.':'Your work,\nat a glance.'}</Text>
  {mode==='home'&&<View style={s.composer}><TextInput value={draft} onChangeText={setDraft} multiline placeholder="Ask AetherVM to do something…" accessibilityLabel="New task" placeholderTextColor="#69737D" style={s.input}/><View style={s.tools}><Text style={s.role}>{target?.name||'Create your first Aether'}</Text><Pressable disabled={!draft.trim()||busy||!target} accessibilityRole="button" accessibilityLabel="Start task" onPress={()=>target&&onSubmit(draft,target.id)} style={[s.send,{opacity:!draft.trim()||busy?.4:1}]}><Text style={{color:'#111315',fontSize:24}}>↑</Text></Pressable></View></View>}
  {mode!=='activity'&&<><View style={s.sectionHead}><Text style={s.sectionTitle}>Your Aethers</Text><Pressable onPress={onCreate} accessibilityRole="button" accessibilityLabel="Create Aether" style={s.add}><Text style={{color:'#ECEFF1',fontSize:26}}>+</Text></Pressable></View><FlatList horizontal data={agents} keyExtractor={a=>a.id} initialNumToRender={3} windowSize={3} showsHorizontalScrollIndicator={false} renderItem={({item})=><View><AgentTile agent={item} onOpen={()=>onOpen(item.id)}/>{mode==='home'&&agents.length>1&&<Pressable accessibilityLabel={`Assign task to ${item.name}`} accessibilityRole="button" onPress={()=>setChosen(item.id)} style={{alignItems:'center',padding:10}}><Text style={{color:target?.id===item.id?'#ECEFF1':'#69737D',fontSize:12}}>{target?.id===item.id?'Selected':'Assign task'}</Text></Pressable>}</View>}/>{!agents.length&&<Pressable onPress={onCreate}><Text style={s.role}>Create a companion to get started →</Text></Pressable>}</>}
  {mode!=='agents'&&<><Text style={[s.sectionTitle,{marginTop:32}]}>Active work</Text>{!running.length&&<Text style={[s.role,{marginVertical:14}]}>All quiet. Something good starts with a task.</Text>}{running.map(a=><Pressable key={a.id} onPress={()=>onOpen(a.id)} style={s.work}><AetherCharacter {...a} size={48} variant={a.avatar} state={taskState(a.job)}/><View style={{flex:1}}><Text style={s.workTitle}>{a.name}</Text><Text numberOfLines={1} style={s.role}>{a.preview||'Working on your task'}</Text><Text style={s.presence}>{a.job?.status==='waiting'?'Needs your help':'In progress'} · {Math.max(0,Math.floor((Date.now()/1000-(a.job?.created||0))/60))}m</Text></View><Text style={s.role}>↗</Text></Pressable>)}<Text style={[s.sectionTitle,{marginTop:28}]}>Recent</Text>{!recent.length&&<Text style={[s.role,{marginVertical:14}]}>Your finished work will appear here.</Text>}{recent.map(a=><Pressable key={a.id} onPress={()=>onOpen(a.id)} style={s.work}><Text style={{color:a.job?.status==='done'?'#8FC8A5':'#E5BD80',fontSize:19}}>{a.job?.status==='done'?'✓':'○'}</Text><View style={{flex:1}}><Text numberOfLines={2} style={s.workTitle}>{a.preview||'Task'}</Text><Text style={s.role}>{a.name} · {new Date((a.job?.created||0)*1000).toLocaleDateString()} · {a.job?.status==='done'?'Completed':a.job?.status}</Text></View></Pressable>)}</>}
 </ScrollView>;
}
const s=StyleSheet.create({page:{padding:24,paddingTop:30,paddingBottom:44,width:'100%',maxWidth:760,alignSelf:'center'},eyebrow:{color:'#949CA4',fontSize:14,marginBottom:12},title:{color:'#ECEFF1',fontSize:36,lineHeight:42,fontWeight:'600',letterSpacing:-1.3,marginBottom:30},composer:{backgroundColor:'#1B1E21',borderRadius:24,padding:16},input:{minHeight:88,maxHeight:180,color:'#ECEFF1',fontSize:17,lineHeight:25,textAlignVertical:'top'},tools:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},send:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:'#ECEFF1'},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:28,marginBottom:12},sectionTitle:{color:'#ECEFF1',fontSize:19,fontWeight:'500',letterSpacing:-.3},add:{width:44,height:44,alignItems:'center',justifyContent:'center'},agent:{width:152,alignItems:'center',paddingVertical:12,paddingHorizontal:8},agentName:{color:'#ECEFF1',fontSize:17,fontWeight:'600',marginTop:6},role:{color:'#949CA4',fontSize:13,lineHeight:21},presence:{color:'#949CA4',fontSize:12,lineHeight:22},work:{flexDirection:'row',alignItems:'center',gap:14,paddingVertical:17},workTitle:{color:'#ECEFF1',fontSize:14,lineHeight:22}});
