(async()=>{
const esbuild=require('../mobile/node_modules/esbuild');const path=require('path');const fs=require('fs');
const root=path.resolve(__dirname,'..');
const options={entryPoints:[path.join(__dirname,'preview.tsx')],bundle:true,platform:'browser',outfile:path.join(__dirname,'preview.js'),jsx:'automatic',alias:{'react-native':path.join(__dirname,'react-native.ts'),'react-native-svg':path.join(root,'mobile/node_modules/react-native-svg/lib/module/ReactNativeSVG.web.js'),'react-native-webview':path.join(__dirname,'native-stubs.tsx'),'expo-secure-store':path.join(__dirname,'native-stubs.tsx'),'expo-status-bar':path.join(__dirname,'native-stubs.tsx'),'expo-clipboard':path.join(__dirname,'native-stubs.tsx'),'expo-document-picker':path.join(__dirname,'native-stubs.tsx'),'expo-file-system/legacy':path.join(__dirname,'native-stubs.tsx'),'expo-sharing':path.join(__dirname,'native-stubs.tsx'),'@react-native-google-signin/google-signin':path.join(__dirname,'native-stubs.tsx')},resolveExtensions:['.web.tsx','.web.ts','.web.js','.tsx','.ts','.jsx','.js','.json'],nodePaths:[path.join(root,'mobile/node_modules')],define:{global:'globalThis','process.env.NODE_ENV':'"production"','process.env.EXPO_PUBLIC_API_URL':'"https://aethervm-api.onrender.com"','process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID':'"qa-only"'},loader:{'.js':'jsx'},plugins:[{name:'static-state-fixture',setup(build){build.onLoad({filter:/mobile\/App\.tsx$/},({path:p})=>({contents:fs.readFileSync(p,'utf8').replace('[editing, setEditing] = useState<Agent | typeof emptyProfile | null>(null)', '[editing, setEditing] = useState<Agent | typeof emptyProfile | null>((globalThis as any).__qaEditing || null)'),loader:'tsx'}));}}]};
await esbuild.build(options);
const js=fs.readFileSync(path.join(__dirname,'preview.js'),'utf8');
fs.writeFileSync(path.join(__dirname,'preview.html'),'<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AetherVM UI QA · Development fixtures</title><style>html,body,#root{margin:0;width:100%;height:100%;background:#111315}#root{display:flex;flex-direction:column}body{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}*{box-sizing:border-box}textarea,input{outline:none}button,a{cursor:pointer}</style><div id="root"></div><script>const qaParams=new URLSearchParams(location.search);const qaRoot=document.getElementById("root");if(qaParams.get("width"))qaRoot.style.width=qaParams.get("width")+"px";if(qaParams.get("height"))qaRoot.style.height=qaParams.get("height")+"px";</script><script>'+js.replace(/<\/script/g,'<\\/script')+'</script>');

})().catch(e=>{console.error(e);process.exit(1)});
