const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import path from 'node:path';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH || undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const root=path.resolve('qa');const failures=[];
const p=await browser.newPage({viewport:{width:390,height:844}});
p.setDefaultTimeout(8000);
p.on('pageerror',e=>{failures.push(e.message);console.log('PAGEERROR',e.message)});
try {
await p.goto('file://'+root+'/preview.html?scenario=empty');
await p.getByText('What should', {exact:false}).waitFor();
await p.locator('iframe').first().waitFor();
await p.waitForTimeout(800);
const frames=p.frames().slice(1);assert(frames.length>0);
assert(await frames[0].evaluate(()=>!!document.querySelector('#head-path')?.getAttribute('d')),'source character is visible');
await p.screenshot({path:root+'/home-390.png'});
await p.getByRole('button',{name:'Open Nova',exact:true}).click();
await p.getByText('What should I work on?',{exact:true}).waitFor();
await p.getByRole('button',{name:'Back Home'}).click();
await p.getByRole('tab',{name:'Agents',exact:true}).click();
await p.getByRole('button',{name:'Create Aether'}).click();
await p.getByLabel('Agent name').fill('Orbit');
await p.getByLabel('bean shape').click();
await p.getByLabel('Glass material').click();
await p.screenshot({path:root+'/create-390.png'});
await p.getByRole('button',{name:'Create agent',exact:true}).click();
await p.getByText('What should I work on?',{exact:true}).waitFor();
await p.getByRole('button',{name:'Back Home'}).click();
await p.getByRole('tab',{name:'Home',exact:true}).click();
await p.getByLabel('New task').fill('Research a small project');
await p.getByRole('button',{name:'Start task'}).click();
await p.getByRole('button',{name:'Expand live computer'}).waitFor();
await p.screenshot({path:root+'/working-390.png'});
await p.goto('file://'+root+'/preview.html?scenario=onboarding');
await p.getByRole('button',{name:'Get started',exact:true}).waitFor();
await p.screenshot({path:root+'/onboarding-390.png'});
await p.getByRole('button',{name:'Get started',exact:true}).click();
await p.getByText('Example session',{exact:true}).waitFor();
await p.getByRole('button',{name:'Continue',exact:true}).click();
await p.getByText('Google Gemini',{exact:true}).waitFor();
await p.getByText('Set up later',{exact:true}).click();
await p.getByLabel('Aether name').waitFor();
await p.getByLabel('Aether name').fill('Nebula');
await p.getByLabel('hex shape').scrollIntoViewIfNeeded();
await p.getByLabel('gem shape').click();
await p.getByRole('button',{name:'Meet your Aether',exact:true}).click();
await p.getByText('Nebula is ready.',{exact:true}).waitFor();
await p.getByRole('button',{name:'Enter AetherVM',exact:true}).click();
await p.getByText('What should',{exact:false}).waitFor();
for(const width of [360,390,700]){await p.setViewportSize({width,height:width===700?390:800});await p.goto('file://'+root+'/preview.html?scenario=empty');await p.getByLabel('New task').waitFor();await p.waitForTimeout(700);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow at '+width)}
await p.emulateMedia({reducedMotion:'reduce'});
await p.setViewportSize({width:360,height:740});
await p.goto('file://'+root+'/preview.html?scenario=empty');
await p.getByLabel('New task').waitFor();
await p.waitForTimeout(500);
const reducedFrame=p.frames().slice(1)[0];
assert(await reducedFrame.evaluate(()=>window.__aetherReduce.matches),'Reduce Motion reaches the original engine');
await p.getByRole('button',{name:'Create Aether'}).click();
await p.getByLabel('Agent name').waitFor();
const heroElement=await p.getByLabel('Aether, blob, curious',{exact:true}).locator('iframe').elementHandle();
const hero=await heroElement.contentFrame();
assert(hero,'Create sheet character has a source engine');
const identity=await hero.evaluate(()=>window.__aetherEngine.stateVersion);
await p.getByLabel('bean shape').click();
await p.waitForTimeout(120);
assert.equal(await hero.evaluate(()=>window.__aetherEngine.stateVersion),identity,'Changing shape preserves engine/state');
assert.equal(await hero.evaluate(()=>window.__aetherEngine.shapeId),'bean');
await p.getByLabel('Agent name').focus();
await p.keyboard.type('One');
assert(await p.getByLabel('Agent name').isVisible());
assert.deepEqual(failures,[]);
console.log('UI checks passed: source SVG rendering, navigation, shape/material creation, Home submission, live-preview reveal, five onboarding screens with skipped key, 360/390/landscape layouts. Reduce Motion reaches the engine; shape changes retain its state; focused input remains visible. Native credentials and VM are mocked.');
} catch(e){console.log((await p.locator('body').innerText()).slice(0,3000));await p.screenshot({path:root+'/failure.png'});throw e} finally {await browser.close();}
