const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import path from 'node:path';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH || undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const root=path.resolve('qa');const failures=[];
const p=await browser.newPage({viewport:{width:390,height:844}});
p.setDefaultTimeout(8000);
p.on('pageerror',e=>{failures.push(e.message);console.log('PAGEERROR',e.message)});
await p.route('https://profile.example.test/avatar.svg',r=>r.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="#bcd6fa"/><circle cx="50" cy="36" r="17" fill="#425d80"/><path d="M18 100v-20a32 32 0 0 1 64 0v20" fill="#425d80"/></svg>'}));
try {
await p.goto('file://'+root+'/preview.html?scenario=empty&photo=1');
await p.getByRole('progressbar').waitFor();
const startup=p.frames().slice(1)[0];
await startup.waitForFunction(()=>window.__aetherEngine?.state==='bouncing' && !!document.querySelector('#head-path')?.getAttribute('d'));
assert.deepEqual(await startup.evaluate(()=>window.__aetherConfig().expressionPool),[2,17]);
await p.screenshot({path:root+'/startup-390.png'});
await p.getByRole('button',{name:'Open Atlas',exact:true}).waitFor();
assert.equal(await p.getByRole('tab').count(),0,'Home keeps the minimal conversation layout');
assert.equal(await p.getByText('AetherVM',{exact:true}).count(),0,'Home has a single profile/search/create toolbar');
assert(await p.locator('img[src="https://profile.example.test/avatar.svg"]').isVisible(),'Stored Google profile image renders');
await p.locator('iframe').first().waitFor();
await p.waitForTimeout(800);
const frames=p.frames().slice(1);assert(frames.length>0);
assert(await frames[0].evaluate(()=>!!document.querySelector('#head-path')?.getAttribute('d')),'source character is visible');
await p.screenshot({path:root+'/home-390.png'});
await p.getByRole('button',{name:'Open Nova',exact:true}).click();
await p.getByText('What should I work on?',{exact:true}).waitFor();
await p.getByRole('button',{name:'Back Home'}).click();
await p.getByRole('button',{name:'Search agents',exact:true}).click();
await p.getByLabel('Search your Aethers').fill('Nova');
assert.equal(await p.getByRole('button',{name:'Open Atlas',exact:true}).count(),0);
await p.getByRole('button',{name:'Open Nova',exact:true}).waitFor();
await p.getByRole('button',{name:'Close search',exact:true}).click();
await p.getByRole('button',{name:'Open account menu',exact:true}).click();
await p.getByText('Settings',{exact:true}).click();
await p.getByText('Google Gemini',{exact:true}).waitFor();
await p.getByRole('tab',{name:'Home',exact:true}).click();
await p.getByRole('button',{name:'Create Aether'}).click();
await p.getByLabel('Agent name').fill('Orbit');
await p.getByLabel('bean shape').click();
await p.getByLabel('Glass material').click();
await p.screenshot({path:root+'/create-390.png'});
await p.getByRole('button',{name:'Create agent',exact:true}).click();
await p.getByText('What should I work on?',{exact:true}).waitFor();
await p.getByRole('button',{name:'Back Home'}).click();
await p.getByRole('button',{name:'Open Atlas',exact:true}).click();
await p.getByLabel('Message your agent').fill('Research a small project');
await p.getByRole('button',{name:'Send message',exact:true}).click();
await p.getByRole('button',{name:'Expand live computer'}).waitFor();
await p.screenshot({path:root+'/working-390.png'});
await p.goto('file://'+root+'/preview.html?scenario=onboarding');
await p.getByRole('button',{name:'Get started',exact:true}).waitFor();
await p.screenshot({path:root+'/onboarding-390.png'});
await p.getByRole('button',{name:'Get started',exact:true}).click();
await p.getByText('Example session',{exact:true}).waitFor();
await p.getByRole('button',{name:'Continue',exact:true}).click();
await p.getByText('Google Gemini',{exact:true}).waitFor();
await p.getByText('Set up later',{exact:true}).click();
await p.getByLabel('Aether name').waitFor();
await p.getByLabel('Aether name').fill('Nebula');
await p.getByLabel('hex shape').scrollIntoViewIfNeeded();
await p.getByLabel('gem shape').click();
await p.getByRole('button',{name:'Meet your Aether',exact:true}).click();
await p.getByText('Nebula is ready.',{exact:true}).waitFor();
await p.getByRole('button',{name:'Enter AetherVM',exact:true}).click();
await p.getByRole('button',{name:'Open Atlas',exact:true}).waitFor();
for(const width of [360,390,700]){await p.setViewportSize({width,height:width===700?390:800});await p.goto('file://'+root+'/preview.html?scenario=empty');await p.getByRole('button',{name:'Open Atlas',exact:true}).waitFor();await p.waitForTimeout(700);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow at '+width)}
await p.emulateMedia({reducedMotion:'reduce'});
await p.setViewportSize({width:360,height:740});
await p.goto('file://'+root+'/preview.html?scenario=empty');
await p.getByRole('button',{name:'Open Atlas',exact:true}).waitFor();
await p.waitForTimeout(500);
const reducedFrame=p.frames().slice(1)[0];
assert(await reducedFrame.evaluate(()=>window.__aetherReduce.matches),'Reduce Motion reaches the original engine');
await p.getByRole('button',{name:'Create Aether'}).click();
await p.getByLabel('Agent name').waitFor();
const heroElement=await p.getByLabel('Aether, blob, curious',{exact:true}).locator('iframe').elementHandle();
const hero=await heroElement.contentFrame();
assert(hero,'Create sheet character has a source engine');
const identity=await hero.evaluate(()=>window.__aetherEngine.stateVersion);
await p.getByLabel('bean shape').click();
await p.waitForTimeout(120);
assert.equal(await hero.evaluate(()=>window.__aetherEngine.stateVersion),identity,'Changing shape preserves engine/state');
assert.equal(await hero.evaluate(()=>window.__aetherEngine.shapeId),'bean');
await p.getByLabel('Agent name').focus();
await p.keyboard.type('One');
assert(await p.getByLabel('Agent name').isVisible());
assert.deepEqual(failures,[]);
console.log('UI checks passed: source SVG rendering, navigation, shape/material creation, conversation submission; home search and account navigation, live-preview reveal, five onboarding screens with skipped key, 360/390/landscape layouts. Reduce Motion reaches the engine; shape changes retain its state; focused input remains visible. Native credentials and VM are mocked.');
} catch(e){console.log((await p.locator('body').innerText()).slice(0,3000));await p.screenshot({path:root+'/failure.png'});throw e} finally {await browser.close();}
