// Development fixtures only. This entry is not included in the Android bundle.
import React from 'react';import {SafeAreaProvider} from 'react-native-safe-area-context';import {createRoot} from 'react-dom/client';import {WorkspaceApp} from '../mobile/App';
const params=new URLSearchParams(location.search),scenario=params.get('scenario')||'empty';let taskState=scenario==='working'?'running':scenario==='error'?'error':'done';
let agents=[{id:'atlas',name:'Atlas',role:'Software engineer',instructions:'Build, debug and test software projects. Keep the work clear and the results useful.',memory:'Verify changes before reporting completion.',avatar:0,shape:'blob',material:'blue-milk',preview:scenario==='empty'?'Software engineer':'Checked the project and completed the task',job:scenario==='empty'?null:{id:'task-1',status:taskState,created:Date.now()/1000-150}},{id:'nova',name:'Nova',role:'Research assistant',instructions:'Research topics and cite primary sources.',memory:'',avatar:1,shape:'bean',material:'mint',preview:'Research assistant',job:null},{id:'pixel',name:'Pixel',role:'Designer',instructions:'Review and improve interfaces.',memory:'',avatar:2,shape:'gem',material:'coral',preview:'Designer',job:null}];
let removed:any[]=[];let messages:any[]=scenario==='empty'?[]:[{id:1,role:'user',text:'Check my project, fix the authentication issue, and run the tests.',created:Date.now()/1000-180},{id:2,role:'assistant',text:scenario==='long'?'## Authentication fixed\n\nThe callback now uses the correct redirect URL.\n\n```typescript\nconst callback = getCallbackUrl();\nreturn redirect(callback);\n```\n\n- Updated the handler\n- Verified login and logout\n- All checks passed\n\n'+('I checked the implementation and verified the results against the expected behavior. '.repeat(35)):'Fixed the callback URL and checked the login flow.\n\n- Updated the authentication handler\n- Verified login and logout\n- Build passes\n\nThe change is ready to review.',created:Date.now()/1000-60}];
if(scenario==='working')messages=[messages[0],{id:2,role:'assistant',text:'I’ll check the project and run its tests.'}];
if(scenario==='compact')messages=[{id:1,role:'user',text:'Hi!'},{id:2,role:'assistant',text:'Hey! How can I help?'},{id:3,role:'user',text:'Find today’s Wordle answer.'},{id:4,role:'assistant',text:'I’ll look it up and check the date.'}];
(window as any).__qaRequests=[];
const events=scenario==='working'?[{kind:'text',message_id:2,text:'I’ll check the project and run its tests.'},{kind:'tool',name:'run_shell',args:{command:'npm test'}},{kind:'result',text:'{"output":"12 tests passed","exit_code":0}'},{kind:'text',message_id:3,text:'The checks passed. I’m reviewing the result.'},{kind:'status',text:'Thinking…'}]:[{kind:'status',text:'Thinking…'}];
window.fetch=async(input:any,options:any={})=>{const url=new URL(String(input)),path=url.pathname,body=options.body?JSON.parse(options.body):{};(window as any).__qaRequests.push(path);let result:any={};if(path==='/removed-agents')result=removed;else if(path.startsWith('/agents/')&&options.method==='DELETE'){const id=path.split('/')[2];removed.push(...agents.filter(a=>a.id===id));agents=agents.filter(a=>a.id!==id);result={ok:true};}else if(path.endsWith('/restore')){const id=path.split('/')[2];result=removed.find(a=>a.id===id);agents.push(result);removed=removed.filter(a=>a.id!==id);}else if(path==='/provider/models')result={models:[{id:'gemini-3.8-flash',name:'Gemini 3.8 Flash'},{id:'gemini-3.1-pro-preview',name:'Gemini 3.1 Pro'}]};else if(path==='/agents'&&options.method==='POST'){result={...body,id:'agent-'+Date.now(),job:null};agents.push(result);}else if(path.startsWith('/agents/')&&options.method==='PUT'){result={...body,id:path.split('/')[2]};agents=agents.map(a=>a.id===result.id?{...a,...result}:a);}else if(path==='/agents')result=agents;else if(path==='/messages')result=url.searchParams.get('agent_id')==='atlas'?messages:[];else if(path.endsWith('/skills'))result=[];else if(path.startsWith('/agents/')&&path.endsWith('/tasks'))result=scenario==='empty'?[]:[agents[0].job];else if(path==='/tasks'&&options.method==='POST'){result={id:'task-1'};taskState='running';if(body.edit_message_id){messages=messages.filter(m=>m.id<=body.edit_message_id);messages.find(m=>m.id===body.edit_message_id).text=body.prompt;}else messages.push({id:Date.now(),role:'user',text:body.prompt});}else if(path==='/tasks/task-1')result={id:'task-1',status:taskState,created:Date.now()/1000-100,events,error:taskState==='error'?'The model quota was reached. Try again later.':null};else if(path==='/workspace/status')result={state:'not_created',control:'agent'};else if(path==='/workspace/list')result=[{name:'src',directory:true,size:0},{name:'README.md',directory:false,size:1812}];else if(path==='/workspace/start')return new Response(JSON.stringify({detail:'QA fixture: a live desktop is not connected in this preview.'}),{status:503});else if(path==='/provider/test')result={ok:true,model_checked:'gemini-2.5-flash',models:[{id:'gemini-2.5-flash',name:'Gemini 2.5 Flash'},{id:'gemini-2.5-pro',name:'Gemini 2.5 Pro'}]};return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});};
createRoot(document.getElementById('root')!).render(<SafeAreaProvider><WorkspaceApp initial={{screen: params.get('screen') as any || 'home'}}/></SafeAreaProvider>);
