import RFB from '@novnc/novnc/lib/rfb.js';
// noVNC (MPL-2.0) handles the continuous authenticated RFB transport.
// Pointer gestures and blue AI cursor are AetherVM code; no polling images.
const surface=document.getElementById('surface'),screen=document.getElementById('screen'),touch=document.getElementById('touch'),cursor=document.getElementById('cursor'),halo=document.getElementById('halo');
const send=data=>window.ReactNativeWebView?window.ReactNativeWebView.postMessage(JSON.stringify(data)):parent.postMessage({desktop:data},'*');
let rfb,zoom=1,pan={x:0,y:0},trackpad=false,reduced=false,pointer={x:640,y:400},drag=false,start=null,longTimer,lastTap=0,moveTime=0,gesture=null,closed=false;
function layout(){const fit=Math.min(innerWidth/1280,innerHeight/800);surface.style.transform=`translate(-50%,-50%) translate(${pan.x}px,${pan.y}px) scale(${fit*zoom})`}
function point(t){const r=surface.getBoundingClientRect();return {x:Math.round((t.clientX-r.left)*1280/r.width),y:Math.round((t.clientY-r.top)*800/r.height)}}
function valid(p){return p.x>=0&&p.y>=0&&p.x<1280&&p.y<800}
function input(action,p={},extra={}){send({kind:'input',action,...p,...extra})}
let target={x:640,y:400},shown={...target},actor='agent',clickTimer,raf;
function paint(){const k=reduced?1:.22;shown.x+=(target.x-shown.x)*k;shown.y+=(target.y-shown.y)*k;cursor.style.transform=`translate(${shown.x}px,${shown.y}px)`;raf=requestAnimationFrame(paint)}
function reaction(event){target={x:event.x,y:event.y};actor=event.actor;cursor.style.opacity='1';cursor.classList.toggle('human',actor==='user');if(event.kind==='click'){clearTimeout(clickTimer);clickTimer=setTimeout(()=>{halo.classList.remove('pulse');void halo.offsetWidth;halo.classList.add('pulse')},reduced?0:130)} }
function configure(config){if(rfb)rfb.disconnect();if(closed)paint();closed=false;reduced=!!config.reduced;document.body.classList.toggle('reduced',reduced);const url=new URL(config.url);if(url.protocol!=='wss:'||!url.hostname.endsWith('.e2b.app')){send({kind:'error'});return}rfb=new RFB(screen,config.url,{credentials:{password:config.password},shared:true});rfb.viewOnly=true;rfb.focusOnClick=false;rfb.scaleViewport=false;rfb.resizeSession=false;rfb.background='#000';rfb.qualityLevel=7;rfb.compressionLevel=2;rfb.addEventListener('connect',()=>{send({kind:'connected'});layout()});rfb.addEventListener('disconnect',()=>{if(!closed)send({kind:'error'})});rfb.addEventListener('securityfailure',()=>send({kind:'error'}));}
function apply(data){if(data.kind==='configure')configure(data.config);else if(data.kind==='cursor')data.events.forEach(reaction);else if(data.kind==='trackpad'){trackpad=data.enabled;zoom=1;pan={x:0,y:0};layout()}else if(data.kind==='recenter'){pointer={x:640,y:400};reaction({...pointer,actor:'user'});input('move',pointer)}else if(data.kind==='reset'){zoom=1;pan={x:0,y:0};layout()}else if(data.kind==='close'){closed=true;rfb?.disconnect();cancelAnimationFrame(raf)}}
window.__desktopApply=apply;addEventListener('message',e=>{if(e.source===parent&&e.data?.desktopCommand)apply(e.data.desktopCommand)});addEventListener('resize',layout);
const distance=(a,b)=>Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),mid=(a,b)=>({x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2});
touch.addEventListener('touchstart',e=>{e.preventDefault();clearTimeout(longTimer);if(e.touches.length===2){if(drag){input('up',pointer);drag=false}const a=e.touches[0],b=e.touches[1];gesture={distance:distance(a,b),mid:mid(a,b),zoom,pan:{...pan},time:Date.now(),moved:false};start=null;return}if(e.touches.length!==1)return;const t=e.touches[0],p=point(t);if(!trackpad&&!valid(p))return;start={t:{clientX:t.clientX,clientY:t.clientY},p,time:Date.now(),moved:false,held:false};if(trackpad&&Date.now()-lastTap<320){drag=true;input('down',pointer)}longTimer=setTimeout(()=>{if(start&&!start.moved){start.held=true;input('click',trackpad?pointer:start.p,{button:'right'})}},550)},{passive:false});
touch.addEventListener('touchmove',e=>{e.preventDefault();clearTimeout(longTimer);if(e.touches.length===2&&gesture){const a=e.touches[0],b=e.touches[1],m=mid(a,b),d=distance(a,b);const dx=m.x-gesture.mid.x,dy=m.y-gesture.mid.y;const pinch=Math.abs(d-gesture.distance)>8;if(pinch||gesture.zoom>1.05){zoom=Math.max(1,Math.min(4,gesture.zoom*d/gesture.distance));pan={x:gesture.pan.x+dx,y:gesture.pan.y+dy};layout();gesture.moved=true}else if(Math.abs(dy)>16&&Date.now()-moveTime>100){input('scroll',point(a),{direction:dy>0?'up':'down',amount:Math.min(6,Math.max(1,Math.round(Math.abs(dy)/18)))});gesture.mid=m;gesture.moved=true;moveTime=Date.now()}return}if(e.touches.length!==1||!start||gesture)return;const t=e.touches[0],dx=t.clientX-start.t.clientX,dy=t.clientY-start.t.clientY;if(Math.hypot(dx,dy)<6&&!start.moved)return;start.moved=true;let p;if(trackpad){const gain=1280/innerWidth;p={x:Math.max(0,Math.min(1279,Math.round(pointer.x+dx*gain))),y:Math.max(0,Math.min(799,Math.round(pointer.y+dy*gain)))};start.t={clientX:t.clientX,clientY:t.clientY}}else{p=point(t);if(!valid(p))return;if(!drag){input('down',start.p);drag=true}}pointer=p;reaction({...p,actor:'user'});if(Date.now()-moveTime>70){input('move',p);moveTime=Date.now()}},{passive:false});
function end(e){e.preventDefault();clearTimeout(longTimer);if(gesture){if(e.touches.length===0){if(!gesture.moved&&Date.now()-gesture.time<400)input('click',trackpad?pointer:point(e.changedTouches[0]),{button:'right'});gesture=null}start=null;return}if(drag){input('up',pointer);drag=false}else if(start&&!start.moved&&!start.held){const p=trackpad?pointer:start.p;input('click',p);reaction({...p,actor:'user',kind:'click'});lastTap=Date.now()}start=null}
touch.addEventListener('touchend',end,{passive:false});touch.addEventListener('touchcancel',e=>{clearTimeout(longTimer);if(drag)input('up',pointer);drag=false;start=null;gesture=null},{passive:false});
// Mouse support for the web build and hardware mouse attached to Android.
touch.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;const p=point(e);if(!valid(p))return;pointer=p;drag=true;touch.setPointerCapture(e.pointerId);input('down',p,{button:e.button===2?'right':'left'})});touch.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!drag)return;const p=point(e);if(valid(p)){pointer=p;if(Date.now()-moveTime>50){input('move',p);moveTime=Date.now()}}});touch.addEventListener('pointerup',e=>{if(e.pointerType==='touch'||!drag)return;drag=false;input('up',pointer,{button:e.button===2?'right':'left'})});touch.addEventListener('contextmenu',e=>e.preventDefault());touch.addEventListener('wheel',e=>{e.preventDefault();const p=point(e);if(e.ctrlKey){zoom=Math.max(1,Math.min(4,zoom*(e.deltaY<0?1.1:.9)));layout()}else if(valid(p))input('scroll',p,{direction:e.deltaY<0?'up':'down',amount:3})},{passive:false});
layout();paint();send({kind:'ready'});
